<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if (($_products = $block->getProductCollection()) && $_products->getSize()): ?>
    
            <ol class="list-inline right_circle_col" >
                <?php foreach ($_products->getItems() as $_product): ?>
				<li>
<div class="circle_small"><a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>"> <?php echo $block->getImage($_product, 'side_column_widget_product_thumbnail')->toHtml(); ?></a></div>
<h4> <?php /* @escapeNotVerified */ echo $this->helper('Magento\Catalog\Helper\Output')->productAttribute($_product, $_product->getName(), 'name') ?></h4>
</li>
                   
                <?php endforeach; ?>
            </ol>
           
      

<?php endif; ?>