<ul class="list-inline right_circle_col">
<li>
<div class="circle_small"><img src="http://demo.suffescom.com/xue1/pub/media/wysiwyg/pro1.jpg" alt="" /></div>
<h4>Joe Knows Coffee1</h4>
</li>
<li>
<div class="circle_small"><img src="http://demo.suffescom.com/xue1/pub/media/wysiwyg/pro2.jpg" alt="" /></div>
<h4>Joe Knows Coffee2</h4>
</li>
<li>
<div class="circle_small"><img src="http://demo.suffescom.com/xue1/pub/media/wysiwyg/pro3.jpg" alt="" /></div>
<h4>Joe Knows Coffee3</h4>
</li>
<li>
<div class="circle_small"><img src="http://demo.suffescom.com/xue1/pub/media/wysiwyg/pro4.jpg" alt="" /></div>
<h4>Joe Knows Coffee4</h4>
</li>
</ul>