<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
$welcomeMessage = $block->getWelcome();
?>
 

<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header_top')->toHtml();?>

<li class="cart_right"><a href="http://magehire.com/para/checkout/cart/">My Cart</a></li>
<div class="search_wrapper">

<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header_adresss')->toHtml();?>

<div class="search_icon">
  <a href="#" id="search_id">  
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px" viewBox="0 0 56.966 56.966" style="enable-background:new 0 0 56.966 56.966;" xml:space="preserve" width="512px" height="512px">
<path d="M55.146,51.887L41.588,37.786c3.486-4.144,5.396-9.358,5.396-14.786c0-12.682-10.318-23-23-23s-23,10.318-23,23  s10.318,23,23,23c4.761,0,9.298-1.436,13.177-4.162l13.661,14.208c0.571,0.593,1.339,0.92,2.162,0.92  c0.779,0,1.518-0.297,2.079-0.837C56.255,54.982,56.293,53.08,55.146,51.887z M23.984,6c9.374,0,17,7.626,17,17s-7.626,17-17,17  s-17-7.626-17-17S14.61,6,23.984,6z" fill="#FFFFFF"/>
</a>
    
</div>
    
<div class="block block-content search_bar">
        <form class="form minisearch" id="search_mini_form" action="http://demo.suffescom.com/xue1/catalogsearch/result/" method="get">
            <div class="field search">
                <label class="label" for="search" data-role="minisearch-label">
                    <span>Search</span>
                </label>
                <div class="control">
                    <input id="search" name="q" value="" placeholder="Search entire store here..." class="input-text" maxlength="128" role="combobox" aria-haspopup="false" aria-autocomplete="both" autocomplete="off" type="text">
                    <div id="search_autocomplete" class="search-autocomplete" style="display: none;"></div>
                                    </div>
            </div>
            <div class="actions">
                <button type="submit" title="Search" class="action search" >
                    <span>Search</span>
                </button>
            </div>
        </form>
</div>
    </div>
